// File generated by FlutterFire CLI / SplitterBud configuration.
// Replace with your project's specific Firebase options if available.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6rGMuI0fxeCEz41UgAFh9RW4-fTsIXMo',
    appId: '1:61729307591:web:9951d2e50ca697497137e2',
    messagingSenderId: '61729307591',
    projectId: 'splitterbuddy2',
    authDomain: 'splitterbuddy2.firebaseapp.com',
    storageBucket: 'splitterbuddy2.firebasestorage.app',
    measurementId: 'G-S6BX5DCFLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAObRPyU5PEp5Gakzm2Nb5GYzMwteo2ENM',
    appId: '1:61729307591:android:91c626b9a0e906be7137e2',
    messagingSenderId: '61729307591',
    projectId: 'splitterbuddy2',
    storageBucket: 'splitterbuddy2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxyybxZHUXgAXX5KK-TNEoz25NV6yRiks',
    appId: '1:61729307591:ios:25f214e454f819a57137e2',
    messagingSenderId: '61729307591',
    projectId: 'splitterbuddy2',
    storageBucket: 'splitterbuddy2.firebasestorage.app',
    iosBundleId: 'com.splitterbuddy.splitterbuddy',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxyybxZHUXgAXX5KK-TNEoz25NV6yRiks',
    appId: '1:61729307591:ios:25f214e454f819a57137e2',
    messagingSenderId: '61729307591',
    projectId: 'splitterbuddy2',
    storageBucket: 'splitterbuddy2.firebasestorage.app',
    iosBundleId: 'com.splitterbuddy.splitterbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6rGMuI0fxeCEz41UgAFh9RW4-fTsIXMo',
    appId: '1:61729307591:web:cebbc8c19301d78c7137e2',
    messagingSenderId: '61729307591',
    projectId: 'splitterbuddy2',
    authDomain: 'splitterbuddy2.firebaseapp.com',
    storageBucket: 'splitterbuddy2.firebasestorage.app',
    measurementId: 'G-FRSPTDCKDH',
  );
}
